### ISSUE TITLE
CentOS 6 compatibility

### ISSUE THREAD

**Issue by hid-jcdhellemmes** [ctrlcctrlv/python-atd#2]
Apparently atd is not compatible with the CentOS 6 at/atq commands output formats:

$ echo "date >> /tmp/FOO" | at now + 1 minute
job 538609 at 2016-11-10 17:52
$ atq
538609  2016-11-10 17:52 a jcdhellemmes

Exception in thread "_CouplerThread-2 (stdin)" Traceback (most recent call last):
  File "./foo.py", line 24, in <module>
    atd.at("/usr/local/foo/bin/foo.py", datetime.datetime.now() + datetime.timedelta(minutes = 1))
  File "/usr/local/foo/lib/atd/atd.py", line 105, in at
    atjob.from_at_stderr(at_stderr)
  File "/usr/local/foo/lib/atd/atq.py", line 195, in from_at_stderr
    raise NotImplementedError('python-atd doesn\'t seem to'+
NotImplementedError: python-atd doesn't seem to support your version of at. Please open an issue. stderr: Garbled time

**Comment by ctrlcctrlv** [comment]
Centos 6 is EOL. If this issue still affects versions of Centos which remain in use, feel free to open another issue.
