### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by Evidlo** [ctrlcctrlv/python-atd#3]
Looks like @gronkdalonka added python3 support.  Maybe he could submit a PR?

**Comment by Gronkdalonka** [comment]
Here you go https://github.com/ctrlcctrlv/python-atd/pull/4 . Haven't done heavy testing yet though

**Comment by ctrlcctrlv** [comment]
The patch looks good to me, and I merged it. I'm actually surprised anyone is using this in production, except the company I work at. 😊
